stages:
  - prebuild
  - build
  - deploy

variables:
  AWS_IMAGE: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

GenerateImages:
  stage: prebuild
  only:
    - master
    - develop
  image: "rust:1.48.0"
  cache:
    key: images_$CI_COMMIT_REF_SLUG
    paths:
      - tools/hashdeps/hashtree/
      - public/assets/photos/generated/
      - tools/image_gen/target/
  script:
    - make images
  artifacts:
    paths:
      - tools/hashdeps/hashtree/
      - public/assets/photos/generated/
      - tools/image_gen/target/
    expire_in: 1 day

Build:
  stage: build
  only:
    - master
    - develop
  image: node:14
  cache:
    key: build_$CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
  script:
    - make build
  artifacts:
    paths:
      - build/
    expire_in: 1 day

DeployStaging:
  stage: deploy
  image: $AWS_IMAGE
  only:
    - develop
  before_script:
    - eval $(aws ecr get-login --no-include-email --region us-west-2 | sed 's|https://||')
  script:
    - aws s3 sync build s3://staging.atelier-mistral.com --delete
    - aws cloudfront create-invalidation --distribution-id E3S4WMILP7S81C --paths "/*"

DeployProduction:
  stage: deploy
  image: $AWS_IMAGE
  only:
    - master
  when: manual
  before_script:
    - eval $(aws ecr get-login --no-include-email --region us-west-2 | sed 's|https://||')
  script:
    - aws s3 sync build s3://atelier-mistral.com --delete
    - aws cloudfront create-invalidation --distribution-id EG9IJEHT3X1J2 --paths "/*"
