stages:
  - prebuild
  - build
  - deploy

variables:
  AWS_IMAGE: amazon/aws-cli:latest
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: $AWS_REGION
  S3_BUCKET_STAGING: $S3_BUCKET_STAGING
  S3_BUCKET_PRODUCTION: $S3_BUCKET_PRODUCTION
  CDN_DISTRIBUTION_ID: $CDN_DISTRIBUTION_ID

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/
    - tools/image_gen/target/

GenerateImages:
  stage: prebuild
  only:
    - master
    - development
  image: "rust:1.48.0"
  script:
    - cd tools/image_gen
    - cargo build --release
    - cd ../../
    - ./tools/image_gen/target/release/image_gen ./public/assets/photos/originals ./public/assets/photos
  artifacts:
    paths:
      - public/assets/photos
    expire_in: 1 day

Build:
  stage: build
  only:
    - master
    - development
  image: node:14
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 day

DeployStaging:
  stage: deploy
  image: $AWS_IMAGE
  only:
    - development
  before_script:
    - eval $(aws ecr get-login --no-include-email --region $AWS_REGION | sed 's|https://||')
  script:
      aws s3 sync build s3://$S3_BUCKET_STAGING --delete

DeployProduction:
  stage: deploy
  image: $AWS_IMAGE
  only:
    - master
  when: manual
  before_script:
    - eval $(aws ecr get-login --no-include-email --region $AWS_REGION | sed 's|https://||')
  script:
      aws s3 sync build s3://$S3_BUCKET_PRODUCTION --delete