name: Production Build

on:
  push:
    branches:
      - master
        
jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.0.x]
     
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Node Packages
      run: |
        npm install
    - name: Build
      run: |
        npm run build
    - name: Deploy
      uses: cameronfyfe/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: west-lens-photography
        AWS_ACCESS_KEY_ID: AKIASMK3GSAIQCT4W5W4
        AWS_SECRET_ACCESS_KEY: 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
        AWS_REGION: us-west-2
        SOURCE_DIR: build
